### ISSUE TITLE
getting this error when executing an example

### ISSUE THREAD

**Issue by aitmlouk** [cadmiumkitty/rdfpandas#1]
AttributeError: module 'rdfpandas' has no attribute 'DataFrame'

**Comment by cadmiumkitty** [comment]
There is a typo in the example. Imports meant to read (similarly to https://github.com/cadmiumkitty/rdf-jupyter/blob/master/work/rdf-roundtrip-example.ipynb)

import rdfpandas.graph
import pandas as pd
import rdflib

I'll fix the README tonight.

**Comment by cadmiumkitty** [comment]
Updated example in the README.
