### ISSUE TITLE
Question: how to access to lower part of RDF hierachy?

### ISSUE THREAD

**Issue by GO5IT** [cadmiumkitty/rdfpandas#10]
Hello. I have a quick question about the use of rdfpandas. Can you answer it?

If I simply do: 
g = rdflib.Graph()
g.parse('to_df_test.ttl', format = 'xml')
df = to_dataframe(g)

It returns only data at the root of the hierarchy, so I wonder how I can get the data the data in a lower hierarchy.
For example, this URI (http://babelnet.org/rdf/data/s00008556n?output=xml) contains:
  <rdf:Description rdf:about="http://babelnet.org/rdf/data/s00008556n?output=xml">
    <rdfs:label>RDF description of S00008556n</rdfs:label>
    <foaf:primaryTopic>
      <skos:Concept rdf:about="http://babelnet.org/rdf/s00008556n">
        <skos:broader>
          <rdf:Description rdf:about="http://babelnet.org/rdf/s00063196n">
            <skos:narrower rdf:resource="http://babelnet.org/rdf/s00008556n"/>
          </rdf:Description>
        </skos:broader>

But, I only get <rdfs:label>RDF description of S00008556n</rdfs:label> of the root resource, and nothing from lower hierarchy.

Questions would be:
a) how can I get e.g. <skos:narrower rdf:resource="http://babelnet.org/rdf/s00008556n"/> with the above code?
b) how can I customise the code to specify a root resource URI? (i.e. <skos:Concept rdf:about="http://babelnet.org/rdf/s00008556n">)

Many thanks!

**Comment by cadmiumkitty** [comment]
Could you please clarify what you mean by "lower hierarchy"? Could you perhaps give an example of expected output?

RdfPandas is a thin wrapper around rdflib and pandas, so it won't do crawling on its own (e.g. retrieving skos:narrower or skos:broader using the URIs present in the dataset).

Here's what I get using your example:

Code:
```
from rdfpandas import to_dataframe
from rdflib import Graph
g = Graph()
g.parse('http://babelnet.org/rdf/data/s00008556n?output=xml', format = 'xml')
df = to_dataframe(g)
df.to_csv('s00008556n.csv', index = True, index_label = "@id")
```

The output that I get is a faithful representation of what is returned by [http://babelnet.org/rdf/data/s00008556n](http://babelnet.org/rdf/data/s00008556n) (Turtle is a lot more readable than XML but it is the same content, just omit the `output` query param).

Output (you can obviously rename columns, this is just the default output):
```
@id,bn-lemon:synsetID{Literal},bn-lemon:synsetType{Literal},bn-lemon:wiktionaryPageLink{URIRef}[0],bn-lemon:wiktionaryPageLink{URIRef}[1],bn-lemon:wiktionaryPageLink{URIRef}[2],dcterms:license{URIRef},lexinfo:derivedForm{URIRef},rdf:type{URIRef},skos:broader{URIRef}[0],skos:broader{URIRef}[1],skos:broader{URIRef}[2],skos:broader{URIRef}[3],skos:exactMatch{URIRef}[0],skos:exactMatch{URIRef}[1],skos:exactMatch{URIRef}[2],skos:exactMatch{URIRef}[3],skos:exactMatch{URIRef}[4],skos:exactMatch{URIRef}[5],rdfs:label{Literal},foaf:primaryTopic{URIRef},lexinfo:pertainsTo{URIRef},skos:narrower{URIRef}
bn:s00008556n,bn:00008556n,NE,wiktionary:Shakespeare,wiktionary:Shakespeareana,wiktionary:Sweet_Swan_of_Avon,http://creativecommons.org/licenses/by-nc-sa/3.0/,bn:s00110499a,skos:Concept,bn:s00028616n,bn:s00044576n,bn:s00063196n,bn:s02788516n,http://dbpedia.org/resource/Spelling_of_Shakespeare's_name,dbpedia:William_Shakespeare,freebase:m.081k8,lemon-WordNet31:111315186-n,http://yago-knowledge.org/resource/Spelling_of_Shakespeare's_name,yago:William_Shakespeare,,,,
bn:s00028616n,,,,,,,,,,,,,,,,,,,,,,bn:s00008556n
bn:s00063196n,,,,,,,,,,,,,,,,,,,,,,bn:s00008556n
bn:s00110499a,,,,,,,bn:s00008556n,,,,,,,,,,,,,,bn:s00008556n,
http://babelnet.org/rdf/data/s00008556n?output=xml,,,,,,,,,,,,,,,,,,,RDF description of S00008556n,bn:s00008556n,,
```

With the above in mind, the answers to your questions appear to be:
a. The first row of the DataFrame is `bn:s00008556n` with all its properties if this is what you are referring to. Exact statement in your question is in the second and third rows of the DataFrame (depending on which one you picked) - `bn:s00063196n skos:narrower bn:s00008556n` and `bn:s00063196n skos:narrower bn:s00008556n`. The dataset has no other triples for `bn:s00063196n` and `bn:s00063196n` subjects, so nothing is added to the DataFrame.
2. The dataset includes the `bn` prefix for `http://babelnet.org/rdf/` and if you don't want it used to create curies just remove the binding for `bn` from the Graph's `NamespaceManager`.

Is this what you are looking for?

**Comment by GO5IT** [comment]
Hello #cadmiumkitty.
Thank you for your explanation! I think I forget to look at my code carefully, which is different from the simple example above. There is no problem. Thanks anyway for useful information.
