### ISSUE TITLE
HTTP access

### ISSUE THREAD

**Issue by GO5IT** [cadmiumkitty/rdfpandas#11]
Sorry, one more question.
Is there a way to cope with HTTP errors when accessing RDF on the web?
If so, how to execute a code with different conditions?
(for instance, If a 404 error occurs, display an error message)
Thank you!

**Comment by cadmiumkitty** [comment]
As with #10 RdfPandas is a thin wrapper around rdflib and pandas, so you would need to deal with any HTTP errors accessing RDF prior to passing rdflib `Graph` to RdfPandas' `to_dataframe`. The way you deal with HTTP errors will depend on the way you access RDF on the web; I believe rdflib will raise `urllib.error.HTTPError` in case of HTTP errors.

**Comment by cadmiumkitty** [comment]
I assume this resolves the issue, but do let me know if you have further questions.
