### ISSUE TITLE
Does JSON-LD work?

### ISSUE THREAD

**Issue by GO5IT** [cadmiumkitty/rdfpandas#12]
Does rdfpandas work with JSON-LD?

I try with 
g.parse('https://dbpedia.org/sparql?default-graph-uri=http%3A%2F%2Fdbpedia.org&query=DESCRIBE%20%3Chttp%3A%2F%2Fdbpedia.org%2Fresource%2F1968%3E&format=application%2Fjson-ld', format = 'jsonld')

But got an error:
rdflib.plugin.PluginException: No plugin registered for (jsonld, <class 'rdflib.parser.Parser'>)

If not supported, it would be highly appreciated if it can support it.
Cheers.

**Comment by cadmiumkitty** [comment]
As with #10 and #11 rdfpandas rely on rdflib to build the `Graph` object. rdflib does support JSON-LD as per https://github.com/RDFLib/rdflib-jsonld (JSON-LD support is built into rdflib starting with 6.0.0, and with earlier versions you need to explicitly install the dependency), there's just a typo in your `format` argument to `parse`, it should be `json-ld`.

With the above said, the code below works, albeit takes a bit of time to build the DataFrame:
```
g = Graph()
g.parse('https://dbpedia.org/sparql?default-graph-uri=http%3A%2F%2Fdbpedia.org&query=DESCRIBE%20%3Chttp%3A%2F%2Fdbpedia.org%2Fresource%2F1968%3E&format=application%2Fjson-ld', format = 'json-ld')
df = to_dataframe(g)
df.to_csv('output.csv', index = True, index_label = "@id")
```

You can also get the same output in Turtle out of dbpedia to get a better default output overall:
```
g.parse('https://dbpedia.org/sparql?default-graph-uri=http%3A%2F%2Fdbpedia.org&query=DESCRIBE%20%3Chttp%3A%2F%2Fdbpedia.org%2Fresource%2F1968%3E&format=application%2Fttl', format = 'ttl')
```

**Comment by GO5IT** [comment]
Thank you. I was using rdflib 5.0 and upgraded to 6.0, but I got another error with your syntax above:

`WindowsError: [Error 123] The filename, directory name, or volume label syntax is incorrect: 'https:\\dbpedia.org\\sparql?default-graph-uri=http%3A%2F`

I think something is wrong with forward and backslashes. I try also raw data (r"....") but does not work either.
By the way your suggestion to use ttl is appreciated, but DBpedia is just an example. There are cases I cannot select different formats. I got the same error with another source with JSON-LD:

`g.parse('https://api.europeana.eu/entity/agent/base/60305?wskey=apidemo', format = 'json-ld')`

**Comment by cadmiumkitty** [comment]
It sounds odd as I tried the code that I shared above and it runs fine. Would you be able to share your code verbatim for the first error?

Re: api.europeana.eu - the source you quoted returns RDF/XML (although I have not tried it with different HTTP `Accept` headers), so changing `json-ld` to `xml` works just fine:
```
g.parse('https://api.europeana.eu/entity/agent/base/60305?wskey=apidemo', format = 'xml')
```

**Comment by GO5IT** [comment]
Before this problem, I just installed rdfpandas, but rdflib was 5.0. All works fine, except JSON-LD. As said, I upgraded to 6.0.2, and this new problem started.

I think problem is not the code (I used exactly the same as yours above except g = rdflib.Graph()). The problem seems to be related to rdflib 6.0.2, because I downgraded to 5.0 and the situation went back to the previous state (ie only JSON-LD does not work).

Then, I wanted to try with 6.0.1, so I tried version change back and forth with pip, and now somehow I cannot specify a version to install in Pycharm. It does not find previous versions, so I can only install the latest (without specifying a version). Now I am confused, but I am still investigating.

**Comment by GO5IT** [comment]
I can confirm that the code works with rdflib 5.0.0 in Pycharm 2021.3 (Community version) , which means JSON-LD cannot be used. The following error occurs:
`rdflib.plugin.PluginException: No plugin registered for (json-ld, <class 'rdflib.parser.Parser'>)`

but all versions from 6.0.0 up return this kind of error for whatever serialisation format is selected: 
`WindowsError: [Error 123] The filename, directory name, or volume label syntax is incorrect:`

So, I would give up using JSON-LD for the time being. If I have time, I could ask rdflib for this. If there is something you could spot a solution, it would be also appreciated.
 
Code used:
```
import rdfpandas
from rdfpandas.graph import to_dataframe
import pandas as pd
import rdflib

g = rdflib.Graph()
# The following returns an error in both 5.0.0 and 6.0.0 up
g.parse('https://api.europeana.eu/entity/agent/base/60305?wskey=apidemo', format = 'json-ld')
# The following works fine with 5.0.0, but returns an error in 6.0.0 up
#g.parse('http://id.worldcat.org/fast/1037825.rdf.xml', format = 'xml')

df = to_dataframe(g)
df.to_csv('rdfpandas_test2.csv', index = True, index_label = "@id")
```

**Comment by cadmiumkitty** [comment]
Thanks, I would have thought that simply adding `rdflib-jsonld` to the requirements file while staying on 5.0.0 of rdflib should solve it. Did you have a chance to try it?

Code I used for the experiment (runs fine):
```
from rdfpandas import to_dataframe
from rdflib import Graph
g = Graph()
g.parse('https://dbpedia.org/sparql?default-graph-uri=http%3A%2F%2Fdbpedia.org&query=DESCRIBE%20%3Chttp%3A%2F%2Fdbpedia.org%2Fresource%2F1968%3E&format=application%2Fjson-ld', format = 'json-ld')
g.serialize('output.ttl', format='ttl', indent=2)
df = to_dataframe(g)
df.to_csv('output.csv', index = True, index_label = "@id")
```

Requirements file  (recreated venv from scratch):
```
pandas
rdfpandas
rdflib-jsonld
```

**Comment by GO5IT** [comment]
Cheers! Unfortunately, rdflib-jsonld with rdflib 5.0.0 generates an error:

```
DeprecationWarning: The rdflib-jsonld package has been integrated into rdflib as of rdflib==6.0.1.  Please remove rdflib-jsonld from your project's dependencies.
  warnings.warn(
```

**Comment by cadmiumkitty** [comment]
I understand that's not ideal, but that's a warning though which should not prevent your code from running. One thing I can do to make things easier is moving rdfpandas dependency to rdflib 6.x.x - let's keep this issue open and I'll get to it in the next couple of weeks.

**Comment by GO5IT** [comment]
Perfect. Your work is very useful and makes my life so much easier. Thanks for the prompt reactions.

**Comment by cadmiumkitty** [comment]
I moved the project to 6.1.1 of rdflib so there is no need to import json-ld plugin separately.

This code works:

```
g = Graph()
g.parse('https://dbpedia.org/sparql?default-graph-uri=http%3A%2F%2Fdbpedia.org&query=DESCRIBE%20%3Chttp%3A%2F%2Fdbpedia.org%2Fresource%2F1968%3E&format=application%2Fjson-ld', format = 'json-ld')
df = to_dataframe(g)
df.to_csv('output.csv', index = True, index_label = "@id")
```

requirements.txt:

```
pandas
rdfpandas==1.1.5
```
