### ISSUE TITLE
Problem with URIRefs

### ISSUE THREAD

**Issue by amemduhoglu** [cadmiumkitty/rdfpandas#6]
Hi,

There is possibly a bug when using URIRefs for predicate or namespaces with signs specifically dashes (-) and hashes (#) etc. The URIRef part that comes after these signs is omitting. For instance, when using `http://www.w3.org/1999/02/22-rdf-syntax-ns#type` it looks `ns1:22` instead of `rdf:type` after serialize. This problem occurred the after release of the new versions because my old working code is broken now.

**Comment by cadmiumkitty** [comment]
Thanks for reporting it. I see there is no test case for URI predicate in rdfpandas, so I'll add it in and release a new version with the fix shortly.

**Comment by cadmiumkitty** [comment]
Fixed in 1.1.1 with URI treatment to match RFC 3986
