### ISSUE TITLE
Issue with to_dataframe import in README guide

### ISSUE THREAD

**Issue by reallyrehan** [cadmiumkitty/rdfpandas#7]
Hi,

I was trying to run the code instructions given in the README was facing the following error,
`name 'to_dataframe' is not defined`

Fixed it by importing it with the following line,
`from rdfpandas.graph import to_dataframe`

I believe this needs to be added in the README.

**Comment by cadmiumkitty** [comment]
Thanks for spotting it, I will include in the next release along with the URI issue fix.

**Comment by cadmiumkitty** [comment]
Fixed in 1.1.1
